# Generated by Django 3.0.4 on 2020-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_details',
            field=models.CharField(default=None, max_length=600),
        ),
    ]
