# Generated by Django 3.0.4 on 2020-03-31 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0003_recipe_preparation_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_details',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
