# Generated by Django 3.0.4 on 2020-03-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20200331_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_details',
            field=models.CharField(default=None, max_length=600),
        ),
    ]
