# Generated by Django 3.0.4 on 2020-03-31 15:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jedzonko.models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_auto_20200331_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(jedzonko.models.DaysOfWeek['Pon'], 'Poniedziałek'), (jedzonko.models.DaysOfWeek['Wt'], 'Wtorek'), (jedzonko.models.DaysOfWeek['Śro'], 'Środa'), (jedzonko.models.DaysOfWeek['Czw'], 'Czwartek'), (jedzonko.models.DaysOfWeek['Pt'], 'Piątek'), (jedzonko.models.DaysOfWeek['Sob'], 'Sobota'), (jedzonko.models.DaysOfWeek['Nie'], 'Niedziela')], max_length=3)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RecepiePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=20)),
                ('order', models.IntegerField(unique=True)),
                ('day_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzonko.DayName')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzonko.Plan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jedzonko.Recipe')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='recepies',
            field=models.ManyToManyField(through='jedzonko.RecepiePlan', to='jedzonko.Recipe'),
        ),
    ]
